export const economyCarDetails = [
  {
    id: 1,
    img: 'https://images.pngnice.com/download/2007/White-Lexus-PNG-Transparent-Image.png',
    carNameEng: 'Lexus || Impala',
    carNameChn: '雷克萨斯 || 雪佛兰英帕拉',
    price: 150,
    perKm: 1.8,
    category: 'Sedan',
    seater: 4,
  },
  {
    id: 2,
    img: 'https://www.motortrend.com/uploads/sites/10/2017/12/2018-chevrolet-impala-1lt-sedan-angular-front.png?fit=around%7C875:492.1875',
    carNameEng: 'Impala',
    price: 150,
    perKm: 1.8,
    category: 'Sedan',
    seater: 4,
  },
  {
    id: 3,
    img: 'https://www.evergreenrentacar.com/wp-content/uploads/toyota-previa-762x456.png',
    carNameEng: 'Previa || Odyssey',
    carNameChn: '丰田普瑞维亚 || 奥德赛',
    price: 150,
    perKm: 2.1,
    category: 'Sedan',
    seater: 4,
  },
  {
    id: 4,
    img: 'https://s3.amazonaws.com/fzautomotive/dealers/5e03e68f02929.png',
    carNameEng: 'Odyssey ',
    price: 150,
    perKm: 2.1,
    category: 'Sedan',
    seater: 4,
  },
  {
    id: 5,
    img: 'https://ymimg1.b8cdn.com/resized/car_model/4036/pictures/3377873/webp_listing_main_2018_Toyota_Hiace__2_.webp',
    carNameEng: 'Toyota Hiace',
    price: 175,
    perKm: 2.75,
    category: 'Coaches',
    seater: 10,
  },
  {
    id: 6,
    img: 'https://cms.eichertrucksandbuses.com/uploads/truck/sub-category/8245d14fef6d736188ecc96a8520e883.png',
    carNameEng: '35 Seater',
    price: 550,
    perKm: 3,
    category: 'Coaches',
    seater: 35,
  },
];
